name: Release

concurrency:
  group: release
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  workflow_dispatch: { }

env:
  # cluster's registry host taken from DC console UI
  registry: cr.airflow.yadc.io/afcdu7pvr25791t0nr3g/2.8.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Stamp version
        run: echo "version=$(make version)" | tee -a "${GITHUB_OUTPUT}"
        id: version
      # Build docker image steps
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Cluster's Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }} # cluster's registry username
          password: ${{ secrets.REGISTRY_PASSWORD }} # cluster's registry password
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: "${{ env.registry }}:${{ steps.version.outputs.version }}"
      - name: Push
        run: |
          docker push ${{ env.registry }}:${{ steps.version.outputs.version }}